### ISSUE TITLE
Unexpected token error.

### ISSUE THREAD

**Issue by sidjain28** [maxlath/wikidata-filter#10]
cat latest-all.json | wikidata-filter --claim P31:Q5 > humans.ndjson

/usr/local/lib/node_modules/wikidata-filter/lib/entity_parser.js:8
    .pipe(filter(line => {
                       ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)

**Comment by maxlath** [comment]
hello @sidjain28, this looks like an error of pre-ES6 Node, could it be that you are using a Node version below `v6.4.0`?
