### ISSUE TITLE
How to filter the triples from wikidata, like (subject, predicate, object) format?

### ISSUE THREAD

**Issue by tangm00** [maxlath/wikidata-filter#11]

**Comment by maxlath** [comment]
could you give a more elaborated example of what you would like to do? I'm not sure to get it right

**Comment by tangm00** [comment]
eg.（Bill Gates, founder of,  Microsoft Inc.）

**Comment by maxlath** [comment]
I can't help much if you can't elaborate more :/
from what I get, you might have more luck looking at the [query service](https://query.wikidata.org/), see [Wikidata Query Help](https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/Wikidata_Query_Help)

**Comment by tangm00** [comment]
thank you anyway

**Comment by rk-zero** [comment]
`wikibase-dump-filter --type both --languages en --keep id,type,claims --simplify`

will solve his usecase

**Comment by maxlath** [comment]
@tangm00 now somehow I get what you mean, sorry ^^

That's too custom for the CLI, so you would need to write a custom filter using the module interface, which could look something like that:
```js
#!/usr/bin/env node
# triple_formatter.js

const { getEntitiesStream } = require('wikibase-dump-filter')
const { claims: simplifyClaims } = require('wikibase-sdk').simplify

getEntitiesStream(process.stdin)
.map(item => {
  const { id, claims } = item
  const simplifiedClaims = simplifyClaims(claims)
  const itemTriples = []
  for (const [ property, propertyClaims ] of Object.entries(simplifiedClaims)) {
    for (const claimValue of propertyClaims) {
      itemTriples.push(JSON.stringify([ id, property, claimValue ]))
    }
  }
  return itemTriples.join('\n') + '\n'
})
.pipe(process.stdout)
```
then, for the shell:
```sh
cat dump.json | ./triple_formatter.js
```
