### ISSUE TITLE
Long List of Claims

### ISSUE THREAD

**Issue by hsaif** [maxlath/wikidata-filter#13]
I'm trying to pass the a long list of claims (+10k) to --claim option as follows:

```
cat latest-all.json.gz | gzip -d | wdfilter --languages en \
		--claim P31:Q5,Q811979,Q294414,Q6256,Q486972,Q5107,Q15916867,Q484652,Q43229,... >> output.json
```
But I'm getting the following error: 

`Argument list too long
`

I was wondering if there a smarter way to do it?

Thanks in advance

**Comment by maxlath** [comment]
[long arguments are a pain](https://www.linuxjournal.com/article/6060) so I added the possibility to [pass the option as a file instead](https://github.com/maxlath/wikidata-filter/blob/master/docs/how_to.md#long-claim-option) (b20b1e2). Can you confirm it works for you?

**Comment by hsaif** [comment]
All running fine with the new option. So I can assume that the claims are filtered correctly based on the input file. 

Many thanks Max

**Comment by maxlath** [comment]
cool!

**Comment by hsaif** [comment]
Something I noticed that passing 25K claims to the filter render the process extremely slow. 
For example, my process has been running for 19 hours now and managed to process ~8M entities only!

**Comment by maxlath** [comment]
I created a dedicated issue: #14
