### ISSUE TITLE
Filter by multiple claims

### ISSUE THREAD

**Issue by LouisFrancini** [maxlath/wikidata-filter#17]
Hi,

I think it would be nice if we could filter by multiple claims at once (either their disjunction or conjunction). This could look something like the & and | syntax the sitelink option uses:

`P42:Q8,Q13&~P666`, `P45:Q10|P32:Q10`, etc.

**Comment by maxlath** [comment]
first implementation done in 642eaa3 and published in `v2.4.0`, [see documentation](https://github.com/maxlath/wikidata-filter/blob/master/docs/how_to.md#claims-logical-operators)
