### ISSUE TITLE
Invalid comparator: ' failed at wikidata-filter@2.4.0 postinstall: `check-node-version --node '>= 6.4.0'`

### ISSUE THREAD

**Issue by praveenogirala** [maxlath/wikidata-filter#22]
Hi Team,
There is an error:
while trying to install the package.

replaced 
postinstall: `check-node-version --node '>= 6.4.0'`

with:
"postinstall": "check-node-version --node \">= 6.4.0\"",

I cloned locally and tried to install with local package

Should we really do this or is there any alternative that I am missing. Could you help me on this.

Thank you in advance!

Regards,
Praveen

**Comment by maxlath** [comment]
hi! I removed the check in `v3.0.2`, assuming that now pretty much everyone should have a NodeJS above v6.4, and that this check creates more problems than it solves then. Could you try to install that new version and see if that works?
