### ISSUE TITLE
Filter formatting

### ISSUE THREAD

**Issue by YovaKem** [maxlath/wikidata-filter#24]
Is it possible to format the following query into a valid filter somehow?

```
SELECT ?work ?workLabel
WHERE
{
  ?work wdt:P31/wdt:P279* wd:Q43229. # instance of any subclass of work of art
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE]". }
}
```

I want to get all entities that are instances of a subclass (of a subclass, etc.) of organizations.

**Comment by maxlath** [comment]
so you could in theory get the list of all [14498](https://query.wikidata.org/#SELECT%20%28COUNT%28%3Forganization%29%20AS%20%3Fcount%29%20WHERE%20%7B%0A%20%20%3Forganization%20wdt%3AP279%2a%20wd%3AQ43229%20.%0A%7D) recursive sub-classes of organization, and write a [long claim option filter](https://github.com/maxlath/wikidata-filter/blob/master/docs/cli.md#long-claim-option) such as:
```sh
echo 'P31:Q55190098,Q54814599,Q53858112,Q53828709,Q53361238' > ./claim
cat entities.json | wikidata-filter --claim ./claim > organizations.ndjson
```
but, while I could't experience it myself, it might get slow (cf #14)

**Comment by YovaKem** [comment]
Thanks, I did that and speed doesn't seem to be a problem.
